Spawning shell within /home/elsa/Conferences-fairness/Conferences-fairness/.venv

(25, 'Inappropriate ioctl for device')
Updating dependencies
Resolving dependencies...

No dependencies to install or update
*** RUNNING SCRIPT get_citation_dummy.py ***

Loading of data, time: 10:45:45
Start author data retreival, time: 10:45:46
Finish author data retreival
Strating building dataframe, time: 22:05:22
Traceback (most recent call last):
  File "/home/elsa/Conferences-fairness/Conferences-fairness/script/get_citation_dummy.py", line 163, in <module>
    main()
  File "/home/elsa/Conferences-fairness/Conferences-fairness/script/get_citation_dummy.py", line 145, in main
    df_author_id['OpenAlex ID'] = ids
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/elsa/Conferences-fairness/Conferences-fairness/.venv/lib/python3.11/site-packages/pandas/core/frame.py", line 4311, in __setitem__
    self._set_item(key, value)
  File "/home/elsa/Conferences-fairness/Conferences-fairness/.venv/lib/python3.11/site-packages/pandas/core/frame.py", line 4524, in _set_item
    value, refs = self._sanitize_column(value)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/elsa/Conferences-fairness/Conferences-fairness/.venv/lib/python3.11/site-packages/pandas/core/frame.py", line 5266, in _sanitize_column
    com.require_length_match(value, self.index)
  File "/home/elsa/Conferences-fairness/Conferences-fairness/.venv/lib/python3.11/site-packages/pandas/core/common.py", line 573, in require_length_match
    raise ValueError(
ValueError: Length of values (67686) does not match length of index (67381)
